### PR TITLE
Update job validations

### PR DESCRIPTION
**Pull request by arosty**
Added validations for job:
rating inside range 1-5
user unique in scope of request (only one job per user per request)

David said: no validation for status. so we have do deal with that in the controller (--> only one job per request should be 'active')

Please also check if you are happy with the 6 statuses

### CODE REVIEW

**Comment by davidmetta** [comment]
ok for me

**Comment by arosty** [comment]
Going to add a validation

**Comment by arosty** [comment]
Added status validation

The helper function is quite long, I am sorry for that. But I didn't see an easier way.

If you accept, all of us have to seed again so that our database has good data.

Always remember in the future, that there can only be one active status (also in the controller)

**Comment by lepetitbelge** [comment]
okay

**Pull request merged**
